services:
  web:
    build: ./web
    ports:
      - 443:443
    develop:
      watch:
        - action: rebuild
          path: ./web/package-lock.json
        - action: sync+restart
          path: ./web/nginx.conf
          target: /etc/nginx/conf.d/nginx.conf
        - action: sync
          path: ./web/dist
          target: /web/static
  app:
    build: .
    restart: always
    environment:
      DATABASE_URL: postgresql://mash:mash@db:5432/time_tracker
      REDIS_URL: redis://cache:6379
      SECRET_KEY: 27a832aa91849382e326b5200f2c3d748a78bac4587e6ffd626dd87d73438f44
      VERSION_NUMBER: 1.0.0
      # MAIL_DEFAULT_SENDER: 'your_email@example.com'
      # MAIL_PASSWORD: 'your_password'
      # MAIL_PORT: 587
      # MAIL_SERVER: 'your_mail_server'
      # MAIL_USE_SSL: False
      # MAIL_USE_TLS: True
      # MAIL_USERNAME: 'your_username'
    expose:
      - 5000
    depends_on:
      - cache
      - db
      - mail
      - web
    develop:
      watch:
        - action: rebuild
          path: ./requirements.txt
          target: /home/appuser/requirements.txt
        - action: sync
          path: ./app
          target: /home/appuser
  cache:
    image: redis:7-alpine
    restart: always
    expose:
      - 6379
  db:
    image: postgres:17-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: mash
      POSTGRES_PASSWORD: mash
      POSTGRES_DB: time_tracker
    volumes:
      - db:/var/lib/postgresql/data
  mail:
    image: axllent/mailpit:v1.23
    restart: always
    volumes:
      - mail:/data
    ports:
      - 8025:8025
    expose:
      - 1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  db:
  mail:
