services:
  web:
    build: ./web
    ports:
      - 443:443
    depends_on:
      - app
  app:
    build: .
    restart: always
    environment:
      - DATABASE_URL=postgresql://mash:mash@db:5432/time_tracker
      - MAILGUN_API_KEY=""
      - MAILGUN_API_URL=""
      - REDIS_URL=redis://cache:6379
      - SECRET_KEY=27a832aa91849382e326b5200f2c3d748a78bac4587e6ffd626dd87d73438f44
      - VERSION_NUMBER=Development
    expose:
      - 5000
    depends_on:
      - cache
      - db
  cache:
    image: redis:7-alpine
    restart: always
    expose:
      - 6379
  db:
    image: postgres:17-alpine
    restart: always
    expose:
      - 5432
    environment:
      POSTGRES_USER: mash
      POSTGRES_PASSWORD: mash
      POSTGRES_DB: time_tracker
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
