version: '3'

services:
  time-tracker:
    build: .
    container_name: time-tracker-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://mash:mash@host.docker.internal:5432/time_tracker
      - FLASK_RUN_PORT=5000
      - GUNICORN_THREADS=2
      - GUNICORN_TIMEOUT=120
      - REDIS_URL=redis://host.docker.internal:6379/0
      - SECRET_KEY=0123456789
    ports:
      - "5000:5000"
    networks:
      - time-tracker
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15.1
    container_name: time-tracker-postgres
    restart: always
    environment:
      - POSTGRES_USER=mash
      - POSTGRES_PASSWORD=mash
      - POSTGRES_DB=time_tracker
    ports:
      - "5432:5432"
    networks:
      - time-tracker

  redis:
    image: redis:7.0
    container_name: time-tracker-redis
    restart: always
    environment:
      - REDIS_PASSWORD=mash
    ports:
      - "6379:6379"
    networks:
      - time-tracker

networks:
  time-tracker:
    driver: bridge
