"""add default tag id

Revision ID: 302f5d0d3fb7
Revises: e354a89547c4
Create Date: 2021-03-07 08:33:21.726556

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "302f5d0d3fb7"
down_revision = "e354a89547c4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_account", sa.Column("default_tag_id", postgresql.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "default_tag_id")
    # ### end Alembic commands ###
