"""remove entry limit

Revision ID: 85a27b4f273d
Revises: 55b4d6070aa0
Create Date: 2021-01-30 23:03:25.102789

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "85a27b4f273d"
down_revision = "55b4d6070aa0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "entry_limit")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account",
        sa.Column(
            "entry_limit",
            sa.INTEGER(),
            server_default=sa.text("120"),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
