"""remove_user_name

Revision ID: a0f729fa8c10
Revises: 89fec1d69a9d
Create Date: 2019-04-23 22:50:41.512508

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f729fa8c10'
down_revision = '89fec1d69a9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_account', 'last_name')
    op.drop_column('user_account', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_account', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user_account', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
