"""create_tag_table

Revision ID: cf04f2a23d02
Revises: a9da40cf2371
Create Date: 2019-07-26 14:12:01.532883

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "cf04f2a23d02"
down_revision = "a9da40cf2371"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tag",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("user_id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name"),
    )
    op.create_index(op.f("ix_tag_user_id"), "tag", ["user_id"], unique=False)
    op.add_column("event", sa.Column("tag_id", postgresql.UUID(), nullable=True))
    op.create_index(op.f("ix_event_tag_id"), "event", ["tag_id"], unique=False)
    op.create_foreign_key(None, "event", "tag", ["tag_id"], ["id"], ondelete="SET NULL")
    op.add_column(
        "user_account",
        sa.Column("tag_limit", sa.Integer(), server_default="5", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "tag_limit")
    op.drop_constraint(None, "event", type_="foreignkey")
    op.drop_index(op.f("ix_event_tag_id"), table_name="event")
    op.drop_column("event", "tag_id")
    op.drop_index(op.f("ix_tag_user_id"), table_name="tag")
    op.drop_constraint("tag_user_id_name_key", "tag", type_="unique")
    op.drop_table("tag")
    # ### end Alembic commands ###
