"""add_activated_at

Revision ID: db8ced4ce2b2
Revises: ffd26960aa0d
Create Date: 2019-06-14 14:57:10.824952

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "db8ced4ce2b2"
down_revision = "ffd26960aa0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account", sa.Column("activated_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "activated_at")
    # ### end Alembic commands ###
