"""add location

Revision ID: fd87ce16f8fd
Revises: 302f5d0d3fb7
Create Date: 2022-08-08 22:58:24.951737

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "fd87ce16f8fd"
down_revision = "302f5d0d3fb7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "location",
        sa.Column("id", postgresql.UUID(), nullable=False),
        sa.Column("user_id", postgresql.UUID(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user_account.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_location_user_id"), "location", ["user_id"], unique=False)
    op.add_column("event", sa.Column("location_id", postgresql.UUID(), nullable=True))
    op.create_index(op.f("ix_event_location_id"), "event", ["location_id"], unique=False)
    op.create_foreign_key(None, "event", "location", ["location_id"], ["id"], ondelete="SET NULL")
    op.add_column(
        "user_account",
        sa.Column("location_limit", sa.Integer(), server_default="3", nullable=False),
    )
    op.add_column(
        "user_account",
        sa.Column("default_location_id", postgresql.UUID(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "default_location_id")
    op.drop_column("user_account", "location_limit")
    op.drop_constraint(None, "event", type_="foreignkey")
    op.drop_index(op.f("ix_event_location_id"), table_name="event")
    op.drop_column("event", "location_id")
    op.drop_index(op.f("ix_location_user_id"), table_name="location")
    op.drop_table("location")
    # ### end Alembic commands ###
