"""add_timezone

Revision ID: ffd26960aa0d
Revises: a0f729fa8c10
Create Date: 2019-05-08 16:12:45.155437

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ffd26960aa0d"
down_revision = "a0f729fa8c10"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_account", sa.Column("timezone", sa.String(), server_default="UTC", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_account", "timezone")
    # ### end Alembic commands ###
