name: Python application

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety flake8 black bandit isort
          pip install -r requirements.txt
      - name: Check dependencies for known security vulnerabilities
        run: safety check -r requirements.txt
      - name: Check code for potential security vulnerabilities
        run: bandit -r .
      - name: Check code formatting
        run: |
          black . -t py311 -l 120 --check
          isort . -c
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings.
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
      - name: Test with pytest
        run: python -m pytest --cov=app --cov-report=term-missing --cov-branch
